-- Protocol-specific medium-change cadence for Trujillo and Microglia.
-- Safe to rerun; calendar dates are generated by app.js from each run's D0.
begin;

update public.differentiation_protocols
set automatic_media_changes = true,
    notes = concat_ws(E'\n\n', nullif(notes, ''), case
      when lower(btrim(name)) like 'trujillo%' and position('Before D31, keep organoids' in coalesce(notes, '')) = 0
        then 'Before D31, keep organoids in each specified medium for one week and replace that same medium between phase transitions. Prefer Monday, Wednesday, and Friday; Tuesday, Thursday, and Sunday are the alternative cadence when needed.'
      when lower(btrim(name)) = 'microglia' and position('After HPC collection and plating' in coalesce(notes, '')) = 0
        then 'After HPC collection and plating, prioritize medium changes on Tuesday and Friday. Cultures may remain up to three full days without a change; avoid weekend work.'
    end),
    notes_pt = concat_ws(E'\n\n', nullif(notes_pt, ''), case
      when lower(btrim(name)) like 'trujillo%' and position('Antes de D31, manter os organoides' in coalesce(notes_pt, '')) = 0
        then 'Antes de D31, manter os organoides uma semana em cada meio especificado e trocar esse mesmo meio entre as transições de fase. Priorizar segunda, quarta e sexta; terça, quinta e domingo são a cadência alternativa quando necessário.'
      when lower(btrim(name)) = 'microglia' and position('Após a coleta e o plaqueamento dos HPCs' in coalesce(notes_pt, '')) = 0
        then 'Após a coleta e o plaqueamento dos HPCs, priorizar trocas de meio às terças e sextas. As culturas podem permanecer até três dias completos sem troca; evitar trabalho no fim de semana.'
    end)
where lower(btrim(name)) like 'trujillo%'
   or lower(btrim(name)) = 'microglia';

commit;
